{% set name = "apache-airflow-providers-yandex" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_yandex-{{ version }}.tar.gz
  sha256: 8a13f0c7145f6c76f5876cef492e23f158751ce6b90a7d5603ea89fb5d8eeec9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }},<3.13
    - apache-airflow >=2.11.0
    # more restrictive for python <3.13
    - yandexcloud >=0.308.0
    # more restrictive for python <3.13
    - yandex-query-client >=0.1.4
    - apache-airflow-providers-common-compat >=1.8.0

test:
  imports:
    - airflow.providers.yandex
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-yandex for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-yandex/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
