{% set name = "apache-airflow-providers-yandex" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_yandex-{{ version }}.tar.gz
  sha256: 54a0bbfd7c3a93b2bb030d7c20d636f96b0d6009f8b7732fbbeee0b603ef9ada

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.6.0
    - yandexcloud >=0.228.0

test:
  imports:
    - airflow.providers.yandex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-yandex for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/yandex/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-yandex/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
