context:
  name: apache-airflow-providers-yandex
  version: "4.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_yandex-${{ version }}.tar.gz
  sha256: 625c1a7768a2f296c4d8481a2c70e4e4c440d455434340eed398a0f88926720f

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    # more restrictive for python >=3.13
    - yandexcloud >=0.376.0
    - yandex-query-client >=0.1.4
    - apache-airflow-providers-common-compat >=1.13.0
    # more restrictive for python >=3.13
    - grpcio >=1.70.0

tests:
  - python:
      imports:
        - airflow.providers.yandex
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-yandex for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-yandex/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
